---
- name: Update Servers
  hosts: all
  roles:
    - role: ubuntu
      when:
        - ansible_facts['os_family'] == "Debian"
        - ansible_facts['distribution'] == "Ubuntu"

    - role: debian
      when:
        - ansible_facts['os_family'] == "Debian"
        - ansible_facts['distribution'] != "Ubuntu"

- handlers:
    - name: Updated server
      debug:
        msg: Updated {{ ansible_facts['hostname'].stdout }}
