- name: Ping Servers to Check
  hosts: "*"
  tasks:
    - name: Ping
      ansible.builtin.ping:

- name: Run Updates
  become: yes
  tasks:
    - name: Update Ubuntu Servers
      hosts: ubuntu
      apt:
        update_cache: yes
        upgrade: yes

    - name: Update Proxmox Servers
      hosts: proxmox, debian
      apt:
        update_cache: yes
        upgrade: yes
