- name: Ping Servers to Check
  hosts: "*"
  tasks:
    - name: Ping
      ansible.builtin.ping:

- name: Run Updates
  hosts: ubuntu, proxmox, debian
  become: yes
  tasks:
    - name: Update Ubuntu Servers
      apt:
        update_cache: yes
        upgrade: yes

    - name: Update Proxmox Servers
      apt:
        update_cache: yes
        upgrade: yes
