- name: Ping Servers to Check
  hosts: "*"
  tasks:
    - name: Ping
      ansible.builtin.ping:

- name: Update Ubuntu Servers
  hosts: ubuntu
  become: yes
  tasks:
    - name: Run Updates
      apt:
        update_cache: yes
        upgrade: yes

- name: Update Proxmox/Debian Servers
  hosts: proxmox, debian
  tasks:
    - name: Run Updates
      apt:
        update_cache: yes
        upgrade: yes
